name: Pronto

on:
  - push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - id: get_base
      run: echo ::set-output name=sha::`git merge-base HEAD origin/dev || git merge-base HEAD origin/master`

    - name: Run Pronto
      uses: adwerx/pronto-ruby@v1.1.0
      with:
        target: ${{ steps.get_base.outputs.sha }}
        runners: >-
          rubocop bundler_audit rails_schema brakeman
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
